#!/usr/bin/env bash

VAULT_TOKEN="$(cat ${HOME}/vault-root-token)"

curl \
    --header "X-Vault-Token: ${VAULT_TOKEN}" \
    --request PUT \
    --data @payload.json \
    "${VAULT_ADDR}/v1/sys/policy/admin"
