#!/usr/bin/env bash

curl \
    --request PUT \
    --data @./data/sys/init/init.json \
    ${VAULT_ADDR}/v1/sys/init \
    -o ${HOME}/vault-init.json

cat ${HOME}/vault-init.json | jq '. | {key: .keys[0]}' | ${HOME}/unseal.json

curl \
    --request PUT \
    --data @${HOME}/unseal.json \
    ${VAULT_ADDR}/v1/sys/unseal \
