#!/usr/bin/env bash

# Initialize Vault
curl \
    --request PUT \
    --data @./data/sys/init/init.json \
    "${VAULT_ADDR}/v1/sys/init" \
    -o "${HOME}/vault-init.json"

jq '. | {key: .keys[0]}' "${HOME}/vault-init.json" > "${HOME}/vault-unseal.json"
jq -r '.root_token' "${HOME}/vault-init.json" > "${HOME}/vault-root-token"

curl \
    --request PUT \
    --data "@${HOME}/vault-unseal.json" \
    "${VAULT_ADDR}/v1/sys/unseal"

rm "${HOME}/vault-init.json" "${HOME}/vault-unseal.json"
