#!/usr/bin/env bash

set -e

VAULT_VERSION="1.2.3"
RELEASES_URL="https://releases.hashicorp.com/vault"
ZIP_NAME="vault_${VAULT_VERSION}_linux_amd64.zip"
ZIP_URL="${RELEASES_URL}/${VAULT_VERSION}/${ZIP_NAME}"
INSTALL_DIR="/opt/hashicorp/vault"
ETC_DIR="/etc/${INSTALL_DIR}"
VAR_DIR="/var/${INSTALL_DIR}"

curl -sO "${ZIP_URL}"
unzip "${ZIP_NAME}"
rm "${ZIP_NAME}"
mv vault "/usr/local/bin/"

setcap cap_ipc_lock=+ep /usr/local/bin/vault

if hash vault 2>/dev/null; then
    echo "Successfully installed $(vault --version)!"
else
    echo "Installation failed!"
fi
