#!/usr/bin/env bash

cp ./vault.service /etc/systemd/system/

mkdir -p /etc/vault
cp ./vault.hcl /etc/vault/
chown -R vault:vault /etc/vault
chmod 640 /etc/vault/vault.hcl

mkdir -p /var/lib/vault
chown -R vault:vault /var/lib/vault
